### ISSUE TITLE
Using NoPluginsCommand Disables All Commands in 1.19.3

### ISSUE THREAD

**Issue by slash1div** [SimplyVanilla/NoPluginsCommand#19]
I first noticed this issue after I upgraded my server to 1.19.3 and it wouldn't let me chat messages.
I disabled secure profile and that fixed it. However, the next day a few people weren't able to use commands.
They rejoined, then they were able to.

Today, I started creating a second server, and I wasn't able to run any commands.
I removed this plugin, then I was able to.

I don't really know how easy this would be to fix, but this is pretty serious for servers running this plugin.
I don't think it was any conflicting plugins, but it may be. Let me know if this is fixed soon, as I depend on this plugin for some backup security.

**Comment by Netherwhal** [comment]
Which version of the plugin are you using? I just checked and I do not see any issues with this plugin and 1.19.3
